### ISSUE TITLE
Get pseudoinverse in browser

### ISSUE THREAD

**Issue by roelandheerema** [mljs/matrix#134] opened 2021-11-23 01:18 UTC
Hi! I'm making a webpage where I'll need to calculate a pseudoinverse. However, I can't get the pseudoInverse function to work in a browser... Any suggestions would be extremely welcome!
`
     <!DOCTYPE html>

    <html>
        <head>
            <title>Test Matrix library</title>
            <script src="https://www.lactame.com/lib/ml/6.0.0/ml.min.js"></script>
        </head>

        <script>
          // ML-MATRIX with web link
            const A = ML.Matrix.eye(6,6); //This works
            const B = A.pseudoInverse(); //This does not work
        </script>
    </html>

`

Thanks very much in advance!

**Comment by stropitek** [comment] 2021-11-23 09:17
Can you give more details about what doesn't work, ideally a reproduction of the issue that we can test ourselves?

**Comment by roelandheerema** [comment] 2021-11-23 14:59
Thanks for the quick reply!

Sure, the error is get is:
_Uncaught TypeError: A.pseudoInverse is not a function_

As shown in the code above, I took the example from the **readme** page:
var pseudoInverse = A.pseudoInverse();

**Comment by targos** [comment] 2021-11-23 15:37
This is an error in the readme. `pseudoInverse` is no longer an instance method (since version 6.0.0):  https://mljs.github.io/matrix/modules.html#pseudoInverse

**Comment by roelandheerema** [comment] 2021-11-23 16:41
Thanks both, that explains it and solved my issue!

First I set the source to an older version:
`<script src="https://www.lactame.com/lib/ml/5.0.0/ml.js"></script>`

And then I could compute my pseudoInverse:
`
      const A = ML.Matrix.eye(6,6); 
      const B = ML.MatrixLib.pseudoInverse(A); 
`

**Comment by Dimava** [comment] 2022-11-05 11:18
Please close this

**Closed** 2022-11-05 11:40 UTC
